CREATE TABLE IF NOT EXISTS users (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Email"         VARCHAR(256) NOT NULL,
    "PasswordHash"  TEXT NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_Email" ON users ("Email");

CREATE TABLE IF NOT EXISTS user_profiles (
    "Id"        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "UserId"    INTEGER NOT NULL,
    "FullName"  TEXT NOT NULL,
    "City"      TEXT NOT NULL,
    "Street"    TEXT NOT NULL,
    "Building"  TEXT NOT NULL,
    "ZipCode"   TEXT NOT NULL,
    CONSTRAINT "PK_user_profiles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_profiles_UserId" ON user_profiles ("UserId");

INSERT INTO users ("Email", "PasswordHash")
SELECT 'user@example.com', 'AQAAAAIAAYagAAAAEDJiv4TCfjhTrXw6+imdSbRu2h9aN6HJzf7ZsK3Hoq6CUrurFiZWjhDhW87Nbpj3dg=='
WHERE NOT EXISTS (SELECT 1 FROM users WHERE "Email" = 'user@example.com');

INSERT INTO user_profiles ("Id", "UserId", "FullName", "City", "Street", "Building", "ZipCode")
SELECT 1, 1, 'Иванов Иван Иванович', 'Москва', 'Тверская', '1', '125009'
WHERE NOT EXISTS (SELECT 1 FROM user_profiles WHERE "UserId" = 1);
