CREATE TABLE IF NOT EXISTS users (
    "Id"            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Email"         VARCHAR(256) NOT NULL,
    "PasswordHash"  TEXT NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_Email" ON users ("Email");

-- test user (password: password123), hash generated with dotnet run --project scripts/hash-password -- "password123" 
INSERT INTO users ("Email", "PasswordHash")
SELECT 'user@example.com', 'AQAAAAIAAYagAAAAEDJiv4TCfjhTrXw6+imdSbRu2h9aN6HJzf7ZsK3Hoq6CUrurFiZWjhDhW87Nbpj3dg=='
WHERE NOT EXISTS (SELECT 1 FROM users WHERE "Email" = 'user@example.com');
