error_log logs/error.log;
pid        logs/nginx.pid;

events {
}

http {
    access_log logs/access.log;

    sendfile on;

    types {
        text/html                             html htm;
        text/css                              css;
        text/javascript                       js mjs;
        image/png                             png;
        image/svg+xml                         svg svgz;
        image/x-icon                          ico;
        application/json                      json;
        font/woff                             woff;
        font/woff2                            woff2;
        application/wasm                      wasm;
    }

    server {
        listen 8080;

        root ../frontend/dist;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://localhost:5000;
        }
    }
}
